### ISSUE TITLE
Script failing while grant permission after adding API services

### ISSUE THREAD

**Issue by krishnareddyg** [CriticalPathTraining/PowerBiEmbedded#2]
Issue: 

System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AzureAppRegUtility.Program.GetServicePrincipalId(String DisplayName) in C:\Users\User\Vijay\PowerBiEmbedded\AzureAppRegUtility\AzureAppRegUtility\Program.cs:line 139
   at AzureAppRegUtility.Program.CreateApplicationForPowerBI(String AppDisplayName) in C:\Users\User\Vijay\PowerBiEmbedded\AzureAppRegUtility\AzureAppRegUtility\Program.cs:line 107
   at AzureAppRegUtility.Program.Main(String[] args) in C:\Users\User\Vijay\PowerBiEmbedded\AzureAppRegUtility\AzureAppRegUtility\Program.cs:line 46

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.

**Comment by krishnareddyg** [comment]
![grantpermission-issue](https://user-images.githubusercontent.com/23409554/28547697-e6eddcfc-7084-11e7-8172-e9fed0e4aa43.jpg)
